### ISSUE TITLE
Merged Sources are not cleaned up when files / folders are moved

### ISSUE THREAD

**Issue by kylekirkby** [linaro-its/jekyll-build-container#79]
When building the 96Boards.org site with the build container, if files/folders are moved between builds then then merged sources will have duplicated files:

```bash
          Conflict: The URL '/srv/source/staging.96boards.org/products/ae/drone/index.html' is the destination for the following pages: products/ae/drone/index.html, _pages/products_ae_drone.html
          Conflict: The URL '/srv/source/staging.96boards.org/products/ae/pcu/index.html' is the destination for the following pages: products/ae/pcu/index.html, _pages/products_ai_pcu.html
          Conflict: The URL '/srv/source/staging.96boards.org/products/ae/ccu/index.html' is the destination for the following pages: products/ae/ccu/index.html, _pages/products_ae_ccu.html
          Conflict: The URL '/srv/source/staging.96boards.org/products/ae/index.html' is the destination for the following pages: products/ae/index.html, _pages/products_ae.html
```

Maybe it would be best to use `rsync` or another cli tool to keep these source folders in sync. Not a massive problem since I can manually remove the files myself but an issue worth noting.

**Comment by pcolmer** [comment]
Unfortunately, this is a consequence of not clearing the `merged_sources` folder between builds - something that the container script used to do but we stopped because of the image caching done within that folder when the 96B site is built.

Once 96B is upgraded to the newer theme, I can restore the original functionality in the script where it clears out the `merged_sources` folder before copying the files into it.

Unfortunately, it isn't as simply as using something like `rsync` because you'd want to use something like `--delete` to remove any files that aren't present in the source folder and (a) that would remove the cached assets and (b) cannot possibly work when you are trying to copy **two** source folders into the one destination folder.

So ... just need to upgrade the theme 😄

**Comment by kylekirkby** [comment]
OK cheers @pcolmer!
